# Change these first
owner: Radiquum # Your GitHub organization or username, where this repository lives
repo: wah.su-uptime # The name of this repository

sites:
  - name: Auth
    url: https://auth.wah.su
  - name: Cloud
    url: https://cloud.wah.su$NC
  - name: Vault
    url: https://vault.wah.su
  - name: Search
    url: https://search.wah.su
  - name: Minecraft ZeroTier Server
    url: $MC

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wah.su
  # baseUrl: /wah.su-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: wah.su Status
  introTitle: This is a status page for services at [wah.su](https://wah.su)
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Report outage
      href: https://github.com/$OWNER/$REPO/issues
    - title: Website
      href: https://wah.su
    - title: Owner
      href: https://bento.me/radiquum
 
workflowSchedule:
  uptime: "*/15 * * * *"
user-agent: Radiquum
      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
